csrutil authenticated-root disable;
diskutil mount /Volumes/MacOS;
Mount -uv /Volumes/MacOS;	
 cd /Volumes/MacOS/System/Library/LaunchAgents;
mkdir tmp;
mv com.apple.ManagedClientAgent.* tmp/;
mv com.apple.mdmclient.* tmp/;
cd ../LaunchDaemons;
mkdir tmp;
mv com.apple.ManagedClient.* tmp/;
mv com.apple.mdmclient.* tmp/;
bless --folder /Volumes/MacOS/System/Library/CoreServices --bootefi --create-snapshot;
